spring:
  application:
    name: cash-buddy
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${PRIV_GOOGLE_CLIENT_ID}
            client-secret: ${PRIV_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo